services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    container_name: db_hibernet
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: miniospring
      MINIO_ROOT_PASSWORD: miniospring
      MINIO_DEFAULT_BUCKETS: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "--console-address", ":9001", "/data" ]

  minio-buckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set dockerminio http://minio:9000  miniospring miniospring;
      /usr/bin/mc mb dockerminio/miniospring;
      exit 0;
      "

  front:
    build:
      context: ./front
    container_name: front
    hostname: front
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./
    container_name: backend
    hostname: backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring
    depends_on:
      - db
      - minio
      - front
